Enable exit on error in pre-push script

diff --git a/etc/git/hooks/pre-push b/etc/git/hooks/pre-push
--- a/etc/git/hooks/pre-push
+++ b/etc/git/hooks/pre-push
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Enable 'exit on error'
+set -e
+
 # Run pytest if there is a tests directory
 if [ -e "tests" ]; then
     pytest --quiet --quiet --tb=no --strict --exitfirst --disable-warnings
